### ISSUE TITLE
Check internal function changes in shinydashboardPlus 

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocGUI#100]
Error in dashboardHeaderPlus... could not find function  "dashboardHeaderPlus"

![image](https://user-images.githubusercontent.com/1698853/111473981-7c109a00-8723-11eb-972f-e43f6c2b52ba.png)

**Comment by lmsimp** [comment]
We thought this may be an issue and seems it is after a major re-name and re-write of functions in  `shinydashboardPlus`

**Comment by lmsimp** [comment]
Lots of breaking changes to address 👎

**Comment by JustynaZitek** [comment]
Hi,
I have exactly the same error :(

**Comment by lmsimp** [comment]
> Hi,I have exactly the same error :(
Hello @JustynaZitek I'm so sorry but this won't be fixed until at least next week. In the meantime the only temporary workaround if to download and install an older version of `shinydashboardPlus`. Best bet is to [install v0.7.5 from CRAN](https://cran.r-project.org/src/contrib/Archive/shinydashboardPlus/). I'm sorry for the delay in getting this fixed there have been major breaking updates which are non-trivial to address.

**Comment by JustynaZitek** [comment]
Hi Lisa,
thanks for the information and your support. Your suggestion helped :)

I have just reported another problem that I am not able to solve.
phenoDisco analysis stopped due to error with estep function a part of
mclust package. It could find it even though the mclust package was active.
Do you have some suggestions on how to solve this issue ?

Thanks again for your help.
Best regards,

Justyna



śr., 24 mar 2021 o 12:36 Lisa Breckels ***@***.***>
napisał(a):

**Comment by lmsimp** [comment]
Fixed in PR #105
